"use client";

import Image from "next/image";
import { useState, type ChangeEvent, type FormEvent } from "react";
import { submitWeddingForm } from "../lib/submitWeddingForm";
import type { WeddingFormPayload } from "../lib/weddingFormTypes";

type FormValues = { firstName1: string; lastName1: string; firstName2: string; lastName2: string; email: string; phone: string; address1: string; address2: string; city: string; state: string; zip: string; fortuneCookieHope: string };
const emptyValues: FormValues = { firstName1: "", lastName1: "", firstName2: "", lastName2: "", email: "", phone: "", address1: "", address2: "", city: "", state: "", zip: "", fortuneCookieHope: "" };
const required: Array<keyof FormValues> = ["firstName1", "lastName1", "email", "phone", "address1", "city", "state", "zip"];

function validate(values: FormValues) { if (required.some((field) => !values[field].trim())) return "Please fill out all required fields."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim())) return "Please enter a valid email address."; if (values.phone.replace(/\D/g, "").length < 10) return "Please enter a valid phone number with at least 10 digits."; return null; }

export function SaveTheDateForm() {
  const [values, setValues] = useState(emptyValues); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [submitted, setSubmitted] = useState(false);
  const onChange = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
  const onSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(null); const message = validate(values); if (message) { setError(message); return; } setIsSubmitting(true); try { const payload: WeddingFormPayload = { ...values, submittedAt: new Date().toISOString(), userAgent: navigator.userAgent, pageUrl: window.location.href, referrer: document.referrer }; await submitWeddingForm(payload); setSubmitted(true); setValues(emptyValues); } catch { setError("We couldn’t save your address. Please try again."); } finally { setIsSubmitting(false); } };
  if (submitted) return <section className="form-card success-panel" aria-live="polite"><p className="eyebrow">Address captured</p><h2>High five. We’ve got it.</h2><p>We’ll only use your information for wedding and pyramid scheme communication.</p><div className="success-image"><Image src="/horse-high-five.png" alt="Katie and Tyler high-fiving on horseback" fill sizes="(max-width: 760px) 100vw, 600px" /></div></section>;
  return <section className="form-card"><div className="form-heading"><p className="eyebrow">Mailing address</p><h2>Where should we send the good stuff?</h2><p>Share one address and contact for your household.</p></div>{error && <p className="form-error" role="alert">{error}</p>}<form onSubmit={onSubmit} noValidate><fieldset><legend>Guest one</legend><div className="form-row"><label>First name *<input name="firstName1" value={values.firstName1} onChange={onChange} autoComplete="given-name" /></label><label>Last name *<input name="lastName1" value={values.lastName1} onChange={onChange} autoComplete="family-name" /></label></div></fieldset><fieldset><legend>Guest two <span>(optional)</span></legend><div className="form-row"><label>First name<input name="firstName2" value={values.firstName2} onChange={onChange} /></label><label>Last name<input name="lastName2" value={values.lastName2} onChange={onChange} /></label></div></fieldset><fieldset><legend>Contact</legend><div className="form-row"><label>Email *<input type="email" name="email" value={values.email} onChange={onChange} autoComplete="email" /></label><label>Phone *<input type="tel" name="phone" value={values.phone} onChange={onChange} autoComplete="tel" /></label></div></fieldset><fieldset><legend>Mailing address</legend><label>Address *<input name="address1" value={values.address1} onChange={onChange} autoComplete="address-line1" /></label><label>Apartment, suite, etc.<input name="address2" value={values.address2} onChange={onChange} autoComplete="address-line2" /></label><div className="form-row form-row--address"><label>City *<input name="city" value={values.city} onChange={onChange} autoComplete="address-level2" /></label><label>State *<input name="state" value={values.state} onChange={onChange} autoComplete="address-level1" /></label><label>ZIP *<input name="zip" value={values.zip} onChange={onChange} autoComplete="postal-code" /></label></div></fieldset><label>What do you hope our next fortune cookie says?<textarea name="fortuneCookieHope" value={values.fortuneCookieHope} onChange={onChange} rows={4} /></label><button className="button" type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving…" : "Save our address"}</button></form><p className="privacy-note">We’ll only use this for wedding communications and invitations.</p></section>;
}
